export enum IActivityKind {
  NONE = 0,
  CUSTOM = 1,
  CREATE_ASSET = 2,
  EDIT_ASSET = 3,
  CREATE_TOKEN = 4,
  EDIT_TOKEN = 5,
  LISTED_TOKEN = 6,
  CANCEL_LISTED_TOKEN = 7,
  TRANSFER_TOKEN = 8,
  COLLECT_TOKEN = 9
}
